### PR TITLE
TranslateTextController.java

### PR DESCRIPTION
**Pull request by Karrrrmen**
update TranslateTextController

### CODE REVIEW

**Comment by HChristinaH** [comment]
could you replace the variables and documentation relating to the User Login application with the ones related to the translate text use case?
also the entity class shouldn't be called User, it should be called TranslateText

**Comment by Karrrrmen** [comment]
sure I've already changed it on my branch, while it requires the approving review of my previous pull request before I make another one.

**Comment by Karrrrmen** [comment]
sure, I've already changed it on my branch, while it requires the approving review of my previous pull request before I make another one.

**Comment by HChristinaH** [comment]
ok ty! the javadoc is still referring to the login use case (ie. line 7) but it should refer to our TranslateText use case. also, what are the username and password parameters for? are we going to the make the users create accounts or was that just left over from the login code? as for the pull request, would it work if you closed this current pull request then make a new pull request?

**Comment by HChristinaH** [comment]
also sorry one more thing, for the execute method in TranslateText controller, i think it also needs an output language parameter

**Pull request closed without merging**
